name: DevSecOps Security Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Semgrep scan
      run: semgrep --config=auto --json > semgrep_results.json

    - name: Generate PDF report
      run: python generate_report.py

    - name: Upload PDF Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: security_report.pdf

